apiVersion: v1
kind: Service
metadata:
  name: mlops-app
  namespace: default
spec:
  selector:
    app: mlops-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
