apiVersion: v1
kind: Service
metadata:
  name: mlops-app
  namespace: default
  labels:                 
    app: mlops-app
spec:
  selector:
    app: mlops-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
